apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-creator-binding
subjects: #This section defines the target of the role
  - kind: User
    name: jjtech-user
    apiGroup: rbac.authorization.k8s.io
roleRef: # referencing the cluster role
  kind: ClusterRole
  name: pod-reader-creator-role
  apiGroup: rbac.authorization.k8s.io